language: generic

services:
  - docker

env:
  matrix:
    - VERSION=apache2.2
    - VERSION=apache2.4
    - VERSION=nginx-1.15.6

install:
  - curl -fsSL get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - cd ${VERSION}
  - make && make test

after_failure:
  - make logs
